# Generated by Django 3.0.2 on 2020-01-26 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gaming.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gaming.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gaming.Game')),
                ('ing_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='gaming.Item')),
                ('ing_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='gaming.Item')),
                ('ing_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='gaming.Item')),
                ('ing_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='gaming.Item')),
                ('ing_5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='gaming.Item')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='gaming.Item')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gaming.Station')),
            ],
        ),
    ]
