# Generated by Django 3.0.2 on 2020-01-26 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaming', '0002_auto_20200126_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='amount',
            field=models.IntegerField(default=1),
        ),
    ]
