# Generated by Django 3.0.2 on 2020-01-26 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gaming', '0003_auto_20200126_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='gaming.Game'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='gaming.Game'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='gaming.Station'),
        ),
        migrations.AlterField(
            model_name='station',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='gaming.Game'),
        ),
    ]
